aosedge/aos_core_lib_cpp

include/aos/common/config/thread.hpp
include/aos/common/thread.hpp
include/aos/common/utils.hpp
tests/common/src/thread_test.cpp

The thread function was stored as static variable inside Thread constructor. But it requires guards for thread-safe initialization of static instances. These guards are part of C++ stdlib in gcc. Disabling them with -fno-threadsafe-statics compiler options may lead to undefined behavior here or other places.
The only place where we can safely store the function is beginning of the thread stack.

[common,thread] Store thread function on the stack

---

include/aos/common/log.hpp
include/aos/common/types.hpp

To avoid using C++ static guard, use simple types for static arrays.

[common,log,types] Use simple types for static array

---

include/aos/common/ocispec.hpp
src/sm/launcher/instance.cpp
tests/sm/launcher/launcher_test.cpp

Cloud puts first element of cmd array into entryPoint[0] and remaining items to cmd array. Update creating runtime config accordingly.

[sm,launcher] Use image entryPoint field as kernel path parameter

---

include/aos/common/crypto/mbedtls/cryptoprovider.hpp
src/common/crypto/mbedtls/cryptoprovider.cpp

Zephyr doesn't provide timegm posix API, use timeutil_timegm for zephyr build.

[common,cryptoprovider] Use timeutil_timegm for zephyr build

---

src/iam/certmodules/pkcs11/pkcs11.cpp

We should not return err if TEE login type env var doesn't exist.

[iam,certmodules] Fix getting TEE login type from env

---

include/aos/common/config.hpp
include/aos/common/crypto.hpp
include/aos/common/cryptoutils.hpp
include/aos/iam/certmodules/certmodule.hpp
src/common/cryptoutils.cpp
tests/common/src/crypto_test.cpp

We use size `len` for string const. As now we use PEM as String, corresponding consts should be renamed.

[common,config] Rename pem size to pem len in config consts

---

src/iam/certmodules/pkcs11/pkcs11.cpp

On clear cert module or validate certs we return error if pkcs11 objects not found. It shouldn't be treated as errors.

[iam,certmodules,pkcs11] Do not return error if object not found

---

src/common/pkcs11/pkcs11.cpp

According to documentation: changes in slot number or initialization will only be visible and effective if C_GetSlotListis called again with NULL slot list. Add NULL slot list read to have up to date slots information.

[common,pkcs11] Fix getting slot list if slots are changed

---

include/aos/common/tools/fs.hpp

This PR reverts recent change in the open function call that leads to compile error on yocto
In function ‘int open(const char*, int, ...)’,
inlined from ‘static aos::Error aos::FS::WriteFile(const aos::String&, const aos::Array<unsigned char>&, uint32_t)’ at /home/mykhailo_lohvynenko/projects/aos/aos_core_lib_cpp/include/aos/common/tools/fs.hpp:421:23:
/opt/aos-vm-dev/4.0.21/sysroots/core2-64-aosvm-linux/usr/include/bits/fcntl2.h:50:31: error: call to ‘__open_missing_mode’ declared with attribute error: open with O_CREAT or O_TMPFILE in second argument needs 3 arguments
50 |           __open_missing_mode ();

[common,tools] Pass permissions for open call

---

include/aos/common/tools/fs.hpp

Zephyr doesn't implement chmod command

[fs] Fix build for zephyr

---

include/aos/common/ocispec.hpp

aos core zephyr will parse this field as JSON_TOK_UINT64.
This PR updates content descriptor type to uint64_t to fix compiler warnings for zephyr build.

[common,ocispec] Change content descriptor size type to uint64_t

---

include/aos/common/tools/array.hpp
include/aos/sm/servicemanager.hpp
src/common/crypto/mbedtls/driverwrapper.cpp

Previously, when a slot was removed, and a new slot was added, the new slot would receive a number already present in the container. For example, if there were two slots with numbers 0 and 1, and slot 0 was deleted, adding a new slot would incorrectly assign it the number 1, which was already in use.

Fix slot numbering

---

src/common/crypto/mbedtls/driverwrapper.cpp

Error log is displayed in wrong branch after recent built-in key fix.

[common,crypto] Fix error log output if built-in key not found

---

include/aos/iam/certprovider.hpp
include/aos/iam/provisionmanager.hpp
src/iam/CMakeLists.txt
src/iam/certprovider/certprovider.cpp
src/iam/certprovider/log.hpp
src/iam/provisionmanager/provisionmanager.cpp
tests/iam/CMakeLists.txt
tests/iam/certprovider/certprovider_test.cpp
tests/iam/provisionmanager/provisionmanager_test.cpp

It is not convenient to use ProvisionManagerItf to retrieve certs URL. Move that part to separate CertProviderItf.

[iam,provisionmanager] Move getting cert to CertProviderItf

---

include/aos/sm/launcher.hpp

Go service manager implementation has operation
version set to 9. Set operation version to 10
due to C++ service manager implementation.

[sm,launcher] Update operation version

---

src/common/monitoring/resourcemonitor.cpp

This patch fetches the monitoring data for the instance when the monitoring is started to prevent possible
resources usage spikes on the first monitoring data fetch.

[common,monitoring] Prevent resource usage spikes on start

---

include/aos/common/tools/map.hpp

Omit creating Pair<K,V>, let Array::EmplaceBack create it in-place

[map] Optimize Map::Emplace method

---

include/aos/common/tools/map.hpp
include/aos/common/tools/utils.hpp

Dont create a Value in Map::Emplace, because Array::EmplaceBack would make it inplace.

Map::Emplace optimization

---

CMakeLists.txt
include/aos/common/cloudprotocol/envvars.hpp
include/aos/common/monitoring/average.hpp
include/aos/common/monitoring/resourcemonitor.hpp
include/aos/common/types.hpp
include/aos/iam/nodemanager.hpp
include/aos/iam/permhandler.hpp
include/aos/sm/launcher.hpp
include/aos/sm/layermanager.hpp
include/aos/sm/resourcemanager.hpp
include/aos/sm/servicemanager.hpp
src/common/CMakeLists.txt
src/common/monitoring/average.cpp
src/common/monitoring/resourcemonitor.cpp
src/iam/CMakeLists.txt
src/iam/nodemanager/nodemanager.cpp
src/iam/permhandler/permhandler.cpp
src/sm/CMakeLists.txt
src/sm/launcher/launcher.cpp
src/sm/layermanager/layermanager.cpp
src/sm/resourcemanager/resourcemanager.cpp
src/sm/servicemanager/servicemanager.cpp

* add stack-usage warning for 4096 byte of stack;
* use space allocator for bit stack data;
* use emplace container api to reduce stack usage.

[all] Add stack-usage (4096) warning for each target

---

include/aos/sm/layermanager.hpp
src/sm/layermanager/layermanager.cpp

This patch reduces stack usage for aos-vm-dev build
```
layermanager.cpp:404:7: error: stack usage is 4416 bytes [-Werror=stack-usage=]
404 | Error LayerManager::InstallLayer(const LayerInfo& layer)
|       ^~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```

[layermanager] Allocate  layer data on static allocator

---

include/aos/sm/launcher/instance.hpp
include/aos/sm/networkmanager.hpp
src/sm/launcher/instance.cpp
src/sm/networkmanager/networkmanager.cpp
tests/include/mocks/networkmanagermock.hpp
tests/sm/networkmanager/networkmanager_test.cpp

Renamed structs like `NetworkParams` and `NetworkParameters` to improve clarity and avoid conflicts in the same namespace.

Rename structs for clarity in network

---

include/aos/common/monitoring/monitoring.hpp
include/aos/common/monitoring/resourcemonitor.hpp
src/common/monitoring/resourcemonitor.cpp
src/sm/launcher/instance.cpp
tests/include/mocks/monitoringmock.hpp

ResourceMonitor::ProcessMonitoring() runs on a separate thread and operates with a delay defined by the "poll period" configuration variable.
As a result, ProcessMonitoring() may execute at a moment when instance monitoring has started, but the instance itself has not yet been launched, leading to the following error: `main aos_servicemanager[1659]: (monitoring) Failed to get instance monitoring data: not found (resourceusageprovider.cpp:324)`

Start instance monitoring before instance is launched

---

src/sm/servicemanager/servicemanager.cpp
tests/sm/servicemanager/servicemanager_test.cpp

This patch fixes a bug that caused the
service manager to remove undamaged services on initialization.

[sm,servicemanager] Remove damaged services on initialization

---

include/aos/sm/launcher/instance.hpp
src/sm/launcher/instance.cpp
tests/sm/launcher/launcher_test.cpp

Aos allocator can't handle recursive allocation as it is designed to allocate data linearly. Serialize allocation to avoid the above issue.

[sm,launcher] Serialize allocation on instance start

---

include/aos/common/config.hpp

We have long mount option for TMP folder, it more than 40 chars. Increase this value up to 64.

[common] Increase AOS_CONFIG_TYPES_FS_MOUNT_OPTION_LEN to 64

---

include/aos/sm/launcher/instance.hpp

Instance allocator size wasn't calculated properly: image spec size should be add for each path.

[sm,launcher] Fix instance static allocator size

---

.github/workflows/build_test.yaml
conan/conanfile.py

Changes to CI should be separated in a dedicated PR due to limitations of workflow's pullrequest target option.

[all] Fix CI build for openssl provider implementation

---

.github/workflows/docker-build.yml

This patch updates the Docker build context in the GitHub Actions workflow to the docker directory,
so conan subfolder is included in the build context.

ci: set docker build context to docker
